
version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: artslave-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/artslave123
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./data/neo4j-init.cypher:/var/lib/neo4j/import/init.cypher
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: artslave-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data:
